#!/usr/bin/env python3
"""Launch RGR phases on Kaggle GPUs from the local box (brief §7).

Workflow:
  python scripts/kaggle_launch.py bundle            # repo+keys+data -> PRIVATE dataset
  python scripts/kaggle_launch.py launch smoke      # CPU connectivity check
  python scripts/kaggle_launch.py launch handcheck  # GPU: §11.1 format check
  python scripts/kaggle_launch.py launch lock_a     # GPU: baseline lock run A
  python scripts/kaggle_launch.py launch lock_b     # GPU: reproducibility run B
  python scripts/kaggle_launch.py status <mode>     # poll
  python scripts/kaggle_launch.py fetch <mode>      # log + runs/ into runs/kaggle/<mode>/

Credentials: Kaggle token from ~/.kaggle/access_token or KAGGLE_API_TOKEN
(file rgr-kaggle at repo root can be copied to either). The bundle dataset
carries rgb-daytona.txt so kernels can execute candidates — it MUST stay
private (this script never passes public=True).
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
import time
from pathlib import Path

REPO = Path(__file__).parents[1]
BUILD = REPO / "runs" / "kaggle_build"
DATASET_SLUG = "rgr-code"

MODES = {
    #  mode       gpu    script args
    "smoke": (False, ["scripts/kaggle_smoke.py"]),
    "handcheck": (True, ["scripts/phase0_lock_baselines.py", "--handcheck"]),
    "lock_a": (True, ["scripts/phase0_lock_baselines.py", "--lock", "--seed-tag", "lock_a"]),
    "lock_b": (True, ["scripts/phase0_lock_baselines.py", "--lock", "--seed-tag", "lock_b"]),
}

RUNNER_TEMPLATE = '''\
# Auto-generated by scripts/kaggle_launch.py — mode: {mode}
import os, shutil, subprocess, sys

# Kaggle mounts datasets at either the new or the classic path.
_CANDIDATES = [
    "/kaggle/input/datasets/{user}/{dataset_slug}",
    "/kaggle/input/{dataset_slug}",
]
SRC = next(p for p in _CANDIDATES if os.path.isdir(p))
WORK = "/tmp/rgr"  # NOT /kaggle/working: the bundle holds keys, output must not
shutil.copytree(SRC, WORK)
os.chdir(WORK)

subprocess.run([sys.executable, "-m", "pip", "install", "-q", "daytona",
                "-U", "bitsandbytes>=0.46.1"], check=True)

env = dict(os.environ, PYTHONPATH=os.path.join(WORK, "src"))
code = subprocess.run([sys.executable] + {script_args!r}, env=env).returncode

# Preserve only results in the kernel output (never the key files).
if os.path.isdir("runs"):
    shutil.copytree("runs", "/kaggle/working/runs", dirs_exist_ok=True)
sys.exit(code)
'''


def api():
    from kaggle.api.kaggle_api_extended import KaggleApi

    kaggle_api = KaggleApi()
    kaggle_api.authenticate()
    return kaggle_api


def username(kaggle_api) -> str:
    user = kaggle_api.get_config_value("username")
    if not user:
        raise RuntimeError("could not resolve kaggle username from credentials")
    return user


def bundle(kaggle_api) -> None:
    """git-archive HEAD + keys + dataset cache -> private Kaggle dataset."""
    user = username(kaggle_api)
    stage = BUILD / "dataset"
    if stage.exists():
        shutil.rmtree(stage)
    stage.mkdir(parents=True)

    # Committed tree only — uncommitted experiments never leak into a run.
    tar = BUILD / "src.tar"
    subprocess.run(["git", "-C", str(REPO), "archive", "-o", str(tar), "HEAD"], check=True)
    subprocess.run(["tar", "-xf", str(tar), "-C", str(stage)], check=True)
    tar.unlink()

    key = REPO / "rgb-daytona.txt"
    if not key.exists():
        raise RuntimeError("rgb-daytona.txt missing — kernels need the sandbox key")
    shutil.copy(key, stage / "rgb-daytona.txt")

    cache = REPO / "data" / "cache"
    if cache.exists():
        shutil.copytree(cache, stage / "data" / "cache")

    (stage / "dataset-metadata.json").write_text(json.dumps({
        "title": DATASET_SLUG,
        "id": f"{user}/{DATASET_SLUG}",
        "licenses": [{"name": "CC0-1.0"}],
    }))

    head = subprocess.run(["git", "-C", str(REPO), "rev-parse", "--short", "HEAD"],
                          capture_output=True, text=True, check=True).stdout.strip()
    try:
        kaggle_api.dataset_status(f"{user}/{DATASET_SLUG}")
        exists = True
    except Exception:
        exists = False
    if exists:
        print(f"updating private dataset {user}/{DATASET_SLUG} (HEAD {head}) ...")
        kaggle_api.dataset_create_version_cli(str(stage), version_notes=f"HEAD {head}",
                                              quiet=True, convert_to_csv=False, dir_mode="zip")
    else:
        print(f"creating private dataset {user}/{DATASET_SLUG} (HEAD {head}) ...")
        kaggle_api.dataset_create_new_cli(str(stage), public=False, quiet=True,
                                          convert_to_csv=False, dir_mode="zip")
    print("bundle pushed. Kaggle processes the version for a minute or two.")


def launch(kaggle_api, mode: str) -> None:
    user = username(kaggle_api)
    gpu, script_args = MODES[mode]
    slug = f"rgr-{mode.replace('_', '-')}"
    stage = BUILD / f"kernel-{mode}"
    if stage.exists():
        shutil.rmtree(stage)
    stage.mkdir(parents=True)

    (stage / "runner.py").write_text(
        RUNNER_TEMPLATE.format(mode=mode, user=user, dataset_slug=DATASET_SLUG,
                               script_args=script_args)
    )
    metadata = {
        "id": f"{user}/{slug}",
        "title": slug,
        "code_file": "runner.py",
        "language": "python",
        "kernel_type": "script",
        "is_private": "true",
        "enable_gpu": "true" if gpu else "false",
        "enable_internet": "true",
        "dataset_sources": [f"{user}/{DATASET_SLUG}"],
        "competition_sources": [],
        "kernel_sources": [],
    }
    if gpu:
        # Kaggle's current torch build dropped sm_60: a P100 assignment fails
        # at model load. Pin the T4 (sm_75, supported).
        metadata["machine_shape"] = "NvidiaTeslaT4"
    (stage / "kernel-metadata.json").write_text(json.dumps(metadata))
    print(f"pushing kernel {user}/{slug} (gpu={gpu}) ...")
    kaggle_api.kernels_push_cli(str(stage), None, None)
    print(f"launched. Poll with: python scripts/kaggle_launch.py status {mode}")


def status(kaggle_api, mode: str, watch: bool = False) -> str:
    user = username(kaggle_api)
    slug = f"rgr-{mode.replace('_', '-')}"
    while True:
        response = kaggle_api.kernels_status(f"{user}/{slug}")
        state = str(getattr(response, "status", response))
        print(f"{slug}: {state}" + (f" ({response.failure_message})"
              if getattr(response, "failure_message", None) else ""))
        terminal = any(s in state.lower() for s in ("complete", "error", "cancel"))
        if not watch or terminal:
            return state
        time.sleep(60)


def fetch(kaggle_api, mode: str) -> None:
    user = username(kaggle_api)
    slug = f"rgr-{mode.replace('_', '-')}"
    out = REPO / "runs" / "kaggle" / mode
    out.mkdir(parents=True, exist_ok=True)
    kaggle_api.kernels_output_cli(f"{user}/{slug}", path=str(out), force=True)
    print(f"output in {out}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="cmd", required=True)
    sub.add_parser("bundle")
    for name in ("launch", "status", "fetch", "watch"):
        p = sub.add_parser(name)
        p.add_argument("mode", choices=MODES)
    args = parser.parse_args()

    kaggle_api = api()
    if args.cmd == "bundle":
        bundle(kaggle_api)
    elif args.cmd == "launch":
        launch(kaggle_api, args.mode)
    elif args.cmd == "status":
        status(kaggle_api, args.mode)
    elif args.cmd == "watch":
        status(kaggle_api, args.mode, watch=True)
    elif args.cmd == "fetch":
        fetch(kaggle_api, args.mode)


if __name__ == "__main__":
    main()
